require("extends.config.noice")
require("extends.config.tree")
require("extends.config.thems")
require("extends.config.treesitter")
require("extends.config.text")
require("extends.config.telescope")
require("extends.config.lua-line")
require("extends.config.bufferline")
require("extends.config.null-ls")
require("extends.config.bookmark")
require("extends.config.markdown")
require("extends.config.snip")

require("extends.lsp.mason")
require("extends.lsp.nvim-lsp")
require("extends.lsp.lspsaga")
require("extends.lsp.cmp")

require("extends.keys")
